___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#060108; font-size:200%; text-align:center; border-radius:10px 10px;">Data Analysis with Python</p>

![Image_Assignment](https://i.ibb.co/cY9HhF7/bnote-assignment.gif)

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#4d77cf; font-size:200%; text-align:center; border-radius:10px 10px;">Assignment 01 (NumPy & Pandas Basics)</p>

<a id="toc"></a>

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Content</p>

* [NUMPY SECTION](#0)
* [PANDAS SECTION](#1)


**In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!**

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Section</p>

<a id="0"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### 1. Import NumPy Library.

In [1]:
# YOUR CODE IS HERE
import numpy as np


### 2. Create an array from my_list = [5, 10, 15, 20, 25]

In [4]:
# YOUR CODE IS HERE
my_list = [5, 10, 15, 20, 25]
c_array= np.array(my_list)
c_array

array([ 5, 10, 15, 20, 25])

### 3. Generate an array of 5x5 with zeros.

In [2]:
# YOUR CODE IS HERE

zarray = np.zeros((5,5))
zarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### 4. Generate an array of 4x4 with ones and assign data type as int.

In [19]:
# YOUR CODE IS HERE
orray=np.ones((4,4), dtype=int)
orray

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 5. Make all the values of the array above with the value of 7.

In [26]:
# YOUR CODE IS HERE
orray.fill(7)
print(orray)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


### 6. Create the previous array above by full() method.

In [28]:
# YOUR CODE IS HERE

fseven= np.full((4,4),7)
fseven

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### 7. Create an array of even integers from 2 to 16 (inclusive).

In [30]:
# YOUR CODE IS HERE

even = np.arange(2,17,2)
even

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [37]:
# YOUR CODE IS HERE

nw=np.arange(25).reshape(5, 5)
nw

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [43]:
# YOUR CODE IS HERE
nw5= np.linspace(0, 25, num=25, endpoint=False).reshape(5, 5)
nw5

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

### 10. Create randomly 5 numbers with numpy.

In [45]:
# YOUR CODE IS HERE
randy=np.random.rand(5)
randy

array([0.53260974, 0.22798488, 0.05814234, 0.12940315, 0.3402412 ])

### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution.

In [48]:
# YOUR CODE IS HERE

rand_new= np.random.rand(5,5)
rand_new

array([[0.86152194, 0.57354997, 0.63634653, 0.4928486 , 0.5584147 ],
       [0.62517281, 0.08872415, 0.63992318, 0.73887102, 0.75963509],
       [0.8563988 , 0.99839207, 0.89740428, 0.59587411, 0.59086316],
       [0.01940798, 0.76824671, 0.23624547, 0.49607753, 0.64691047],
       [0.06096557, 0.86547128, 0.55224473, 0.8567064 , 0.03075388]])

### 12. Create a 3*4 array of random int numbers between 20 and 50.

In [3]:
# YOUR CODE IS HERE
ud= np.random.randint(20, 50, size=(3, 4))
ud


array([[34, 20, 43, 29],
       [31, 20, 34, 36],
       [20, 24, 25, 46]])

### 13. Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [62]:
# YOUR CODE IS HERE
ranarr= np.random.randint(50,size=(6, 8))
ranarr

array([[32, 11, 22,  5, 18, 24,  9,  7],
       [ 7, 26, 26, 17, 35, 38, 19, 38],
       [33, 45, 25, 22,  8, 43, 40,  2],
       [34, 13, 39, 32, 26, 42,  4, 35],
       [22,  7, 23, 48, 28,  0, 39, 19],
       [18, 34, 27,  6, 29, 19, 31, 21]])

In [68]:
# YOUR CODE IS HERE (RESHAPING WITH NUM)

ranarr = np.random.random(48)
reshaped_array1 = ranarr.reshape(6, 8)
reshaped_array1


array([[0.39051029, 0.50598252, 0.40221556, 0.01575099, 0.21172588,
        0.40944256, 0.70255672, 0.38975339],
       [0.0875853 , 0.90449267, 0.66024533, 0.9258798 , 0.56386905,
        0.47912686, 0.48156757, 0.84420106],
       [0.81227015, 0.88466253, 0.40524261, 0.19504961, 0.90232038,
        0.93178792, 0.40898933, 0.97061659],
       [0.46732828, 0.93981494, 0.87232533, 0.5509671 , 0.01442481,
        0.704751  , 0.08418393, 0.46910561],
       [0.2322055 , 0.10711246, 0.24842528, 0.74448679, 0.4124325 ,
        0.42322558, 0.18248121, 0.67491644],
       [0.8859324 , 0.83266598, 0.22484377, 0.20326037, 0.8710079 ,
        0.1949816 , 0.83544479, 0.45452334]])

In [70]:
# YOUR CODE IS HERE (RESHAPING WITH -1)



[[0.39051029 0.50598252 0.40221556 0.01575099 0.21172588 0.40944256
  0.70255672 0.38975339]
 [0.0875853  0.90449267 0.66024533 0.9258798  0.56386905 0.47912686
  0.48156757 0.84420106]
 [0.81227015 0.88466253 0.40524261 0.19504961 0.90232038 0.93178792
  0.40898933 0.97061659]
 [0.46732828 0.93981494 0.87232533 0.5509671  0.01442481 0.704751
  0.08418393 0.46910561]
 [0.2322055  0.10711246 0.24842528 0.74448679 0.4124325  0.42322558
  0.18248121 0.67491644]
 [0.8859324  0.83266598 0.22484377 0.20326037 0.8710079  0.1949816
  0.83544479 0.45452334]]


In [71]:
# YOUR CODE IS HERE (RESHAPING WITH -1)
reshaped_array2 = ranarr.reshape(6, -1)
print(reshaped_array2)


[[0.39051029 0.50598252 0.40221556 0.01575099 0.21172588 0.40944256
  0.70255672 0.38975339]
 [0.0875853  0.90449267 0.66024533 0.9258798  0.56386905 0.47912686
  0.48156757 0.84420106]
 [0.81227015 0.88466253 0.40524261 0.19504961 0.90232038 0.93178792
  0.40898933 0.97061659]
 [0.46732828 0.93981494 0.87232533 0.5509671  0.01442481 0.704751
  0.08418393 0.46910561]
 [0.2322055  0.10711246 0.24842528 0.74448679 0.4124325  0.42322558
  0.18248121 0.67491644]
 [0.8859324  0.83266598 0.22484377 0.20326037 0.8710079  0.1949816
  0.83544479 0.45452334]]


## Numpy Indexing and Selection

### Create an array named "mat" in accordence with the desired output below.

In [40]:
# YOUR CODE IS HERE
mat= np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 14. Using the array above, write a code that reproduces the desired output shown below.<br>

In [41]:
# YOUR CODE IS HERE
sliced = mat[1:3, 1:3]
sliced

array([[ 6,  7],
       [10, 11]])

### 15. Get the 1st column (index number 0) of the array above.

In [20]:
# YOUR CODE IS HERE
fc= mat[:,0]
fc

array([ 1,  5,  9, 13])

### 16. Get the values in 2nd row (index number 1) for every 2 step.

In [21]:
mat


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [22]:
# YOUR CODE IS HERE
step= mat[1, ::2]
step

array([5, 7])

### 17.Assign 77 to every cell in 3rd column.

In [42]:
# YOUR CODE IS HERE
mat[::,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### 18. (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [24]:
a=mat[1,0],mat[3,2]

In [25]:
# YOUR CODE IS HERE
son= np.array([a])
son

array([[ 5, 77]])

### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [26]:
# YOUR CODE IS HERE
tod= mat[1::2, 0::2]
tod


array([[ 5, 77],
       [13, 77]])

## NumPy Operations

### 20. Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [38]:
ok=np.array([mat < 10])
ok

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True, False, False, False],
        [False, False, False, False]]])

In [39]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
ondankucuk= np.sum(mat[mat < 10])
ondankucuk


45

In [29]:
onikidenbuyuk=np.sum(mat[mat > 12])
onikidenbuyuk

351

In [30]:
# LET US FIND THE VALUES SMALLER THAN 10 IN "mat"

# YOUR CODE IS HERE

ok=np.array(mat[mat < 10])
ok

array([1, 2, 4, 5, 6, 8, 9])

In [31]:
# LET US FIND THE VALUES BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE

ooi=np.array(mat[mat > 12])
ooi

array([77, 77, 77, 13, 14, 77, 16])

In [45]:
# LET US SUM THE VALUES SMALLER THAN 10 AND BIGGER THAN 12 IN "mat"

# YOUR CODE IS HERE


sum_smaller_than_10 = np.sum(mat[mat < 10])


sum_bigger_than_12 = np.sum(mat[mat > 12])

# Total sum
total_sum = sum_smaller_than_10 + sum_bigger_than_12
print("Total sum of values smaller than 10 and bigger than 12:", total_sum)

Total sum of values smaller than 10 and bigger than 12: 103


### 21. Get the standard deviation (std) of the result above.

In [44]:
values_to_consider = np.concatenate((mat[mat < 10], mat[mat > 12]))
values_to_consider

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 13, 14, 15, 16])

In [43]:
# YOUR CODE IS HERE



Standard deviation of the values: 4.921874853245043


### 22. Get the sum of the 2nd column in the original "mat".

In [14]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE
mat[::,2]=77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [47]:
# LET OBTAIN THE ORIGINAL ARRAY OF "mat"

# YOUR CODE IS HERE

mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
# YOUR CODE IS HERE
mat[3,3]*2


32

### 23. Get the median, mean and std of 3rd column in "mat".

In [50]:
# LET US REMEMBER OUR ARRAY OF "mat"

# YOUR CODE IS HERE

mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [53]:
# LET US ASSIGN THE COLUMN WE ARE INTERESTED IN TO A VARIABLE

# YOUR CODE IS HERE
mat[:,2].reshape(4,1)


array([[ 3],
       [ 7],
       [11],
       [15]])

In [56]:
# WHAT IF WE ARE INTERESTED IN THE 3RD ROW?

# YOUR CODE IS HERE

mat[2]

array([ 9, 10, 11, 12])

In [65]:
# LET US GET MEDIAN VALUE

# YOUR CODE IS HERE
media_one= np.median(mat[:,2])
media_two= np.median(mat[2])
print(media_one)
media_two


9.0


10.5

In [66]:
# LET US GET MEAN VALUE

# YOUR CODE IS HERE

medi_one= np.mean(mat[:,2])
medi_two= np.mean(mat[2])
print(medi_one)
medi_two

9.0


10.5

In [67]:
# LET US GET STANDART DEVIATION (std) VALUE

# YOUR CODE IS HERE
mei_one= np.std(mat[:,2])
mei_two= np.std(mat[2])
print(mei_one)
mei_two


4.47213595499958


1.118033988749895

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Pandas Section</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true"
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

### Import Pandas Library

In [68]:
import pandas as pd

### Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements.*

[pandas.read_csv() function --> (pandas official document)](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html)

In [99]:
!pip install py7zr

import py7zr
with py7zr.SevenZipFile('Salaries.7z', mode='r') as z:
    z.extractall()

   ---------------------------------------- 0.0/67.9 kB ? eta -:--:--
   ------------------ --------------------- 30.7/67.9 kB 660.6 kB/s eta 0:00:01
   ---------------------------------------- 67.9/67.9 kB 739.3 kB/s eta 0:00:00
   ---------------------------------------- 0.0/357.3 kB ? eta -:--:--
   --- ------------------------------------ 30.7/357.3 kB 1.3 MB/s eta 0:00:01
   ------- ------------------------------- 71.7/357.3 kB 787.7 kB/s eta 0:00:01
   ----------- -------------------------- 112.6/357.3 kB 939.4 kB/s eta 0:00:01
   --------------- ---------------------- 143.4/357.3 kB 853.3 kB/s eta 0:00:01
   -------------------- ----------------- 194.6/357.3 kB 908.0 kB/s eta 0:00:01
   ----------------------- -------------- 225.3/357.3 kB 860.2 kB/s eta 0:00:01
   --------------------------- ---------- 256.0/357.3 kB 874.6 kB/s eta 0:00:01
   ------------------------------ ------- 286.7/357.3 kB 842.9 kB/s eta 0:00:01
   --------------------------------- ---- 317.4/357.3 kB 855

  You can safely remove it manually.


In [83]:
# LET US READ Salaries.csv

df = pd.read_csv('Salaries.csv')


In [84]:
# LET US LOOK AT THE FIRST 5 ROWS

# YOUR CODE IS HERE
df.head()


Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

Desired Output:

![image.png](https://i.ibb.co/6BTmGX8/assignment1a.png)

In [86]:
# LET US GET A SAMPLE

# YOUR CODE IS HERE
sample_df = df.sample()
sample_df

Id  EmployeeName          JobTitle   BasePay  OvertimePay  \
101869  101870  Earl A Scott  Transit Operator  22401.85      6328.66   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
101869    224.92  10546.09  28955.43          39501.52  2013    NaN   

               Agency  Status  
101869  San Francisco     NaN

Desired Output (WATCH OUT! Your output may NOT be the same as the one):

![image.png](https://i.ibb.co/mcsCxxC/assignment1b.png)

In [89]:
# YOUR CODE IS HERE

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [90]:
# LET US GET SOME DESCRIPTIVE MEASUREMENTS

# YOUR CODE IS HERE

df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448840    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

Desired Output:

![image.png](https://i.ibb.co/ftMP67H/assignmnet1c.png)

### How many different year values are there?

In [100]:
# YOUR CODE IS HERE

hmy= df['Year'].value_counts()
hmy

Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: count, dtype: int64

In [98]:
# LET US FIND THE NUMBER OF UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE

uniqueyear = df['Year'].nunique()
uniqueyear

4

In [101]:
# LET US FIND THE UNIQUE VALUES IN THE COLUMN OF "Year"

# YOUR CODE IS HERE

uniqee = df['Year'].unique()
uniqee

array([2011, 2012, 2013, 2014], dtype=int64)

### Print out max and avg values in the column of "Totalpay".

In [105]:
# LET US FIND THE MAXIMUM TOTALPAY

# YOUR CODE IS HERE

max_val = df['TotalPay'].max()
max_val

567595.43

In [106]:
# LET US FIND THE AVERAGE TOTALPAY

# YOUR CODE IS HERE

avg_val = df['TotalPay'].mean()
avg_val

74768.32197169267

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [ ]:
# YOUR CODE IS HERE



In [109]:
count_bigger = df[df['TotalPay']>avg_val]
count_bigger

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

Desired Output:

![image.png](https://i.ibb.co/nj84FbZ/assignment1d.png)

In [ ]:
# YOUR CODE IS HERE



### How much does ALBERT PARDINI make money (including benefits)?

In [112]:
# YOUR CODE IS HERE
min_val = df['TotalPay'].min()
min_val


-618.13

### Who is the lowest paid person?

In [123]:
lowest_paid_person = df.loc[df['TotalPay'].idxmin(), 'EmployeeName']
lowest_paid_person

'Joe Lopez'

In [124]:
# YOUR CODE IS HERE



### What are the unique Jobs in dataset?

In [126]:
# YOUR CODE IS HERE

uniq_job = df['JobTitle'].unique()

### List the top 3 least common Jobs in the dataset.

In [127]:
# YOUR CODE IS HERE

least_common_jobs = df['JobTitle'].value_counts().nsmallest(3)
least_common_jobs


JobTitle
BOARD SECRETARY - MUNICIPAL TRANSPORTATION AGENC    1
FEASIBILITY ANALYST, PORT                           1
ELECTROENCEPHALOGRAPH TECHNICIAN I                  1
Name: count, dtype: int64

### How many people earned more than avg in 2012?

In [129]:
# YOUR CODE IS HERE

df2012 = df[df['Year']==2012]

In [132]:
avg2012= df2012['TotalPay'].mean()

In [133]:
avg_more= df2012[df2012['TotalPay']>avg2012]
avg_more

Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
60315  60316       William Jones                     Manager V   74195.53   
60463  60464       Carol Pirolli                 Special Nurse   72375.35   
60717  60718      Jocelyn Weiler                 Special Nurse   69504.72   
60733  60734        Diana Edward                 Special Nurse   76434.48   
60900  60901       Mary Ann Hauf                 Special Nurse   73681.40   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
60315         0.00      0.00   5989.25   74195.53          80184.78  2012   
60463      2057.90   3559.98   1620.16   77993.23          79613.39  2012   
60717      5190.55   2658.79   1394.10   77354.06          78748.16  2012   
60733         0.00    834.73   1433.57   77269.21          78702.78  2012   
60900      2723.40     46.54   1477.34   76451.34          77928.68  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
60315    NaN  San Francisco     NaN  
60463    NaN  San Francisco     NaN  
60717    NaN  San Francisco     NaN  
60733    NaN  San Francisco     NaN  
60900    NaN  San Francisco     NaN  

[16944 rows x 13 columns]

### How many people have a title of Manager in their jobs?

In [136]:
# USE APPLY FUNCTION

# YOUR CODE IS HERE

filter_manager= df[df['JobTitle']== 'Manager']
filter_manager_count = filter_manager. counts()
filter_manager_count

AttributeError: 'DataFrame' object has no attribute 'counts'

In [140]:
def contains_manager(title):
    return 'Manager' in title


# Apply the function to the JobTitle column and sum the True values
manager_count = df['JobTitle'].apply(contains_manager).sum()
manager_count

3080

3080

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [143]:
# YOUR CODE IS HERE
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

Desired Output:

![image.png](https://i.ibb.co/ZgFCbPm/assignment1e.png)

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [145]:
# YOUR CODE IS HERE

sal_new = df.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new.head()

EmployeeName                                        JobTitle  \
0     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43  
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28  
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91  
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61  
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19

Desired Output:

![image.png](https://i.ibb.co/s2CYS7H/assignment1f.png)

### Print out the names of the employees who earn more than min but less than avg.

In [148]:
min_val = df['TotalPay'].min()
min_val

-618.13

In [147]:
avg_val = df['TotalPay'].mean()
avg_val

74768.32197169267

In [149]:

filtered_employees = df[(df['TotalPay'] > min_val) & (df['TotalPay'] < avg_val)]
filtered_employees

Id       EmployeeName                          JobTitle   BasePay  \
15847    15848  TATYANA ROTENBERG     ELIGIBILITY WORKER SUPERVISOR  73155.87   
15848    15849        WINSTON HOM              AUTOMOTIVE MACHINIST  73554.60   
15849    15850       CRAIG RIGLER  SENIOR FARE COLLECTIONS RECEIVER  64694.49   
15850    15851          WENDY TAN                            PORTER  48472.40   
15851    15852     KENNETH BREWER                  WATERSHED KEEPER  60206.62   
...        ...                ...                               ...       ...   
148648  148649        Leon Walker                         Custodian      0.00   
148649  148650      Roy I Tillery                         Custodian      0.00   
148650  148651       Not provided                      Not provided       NaN   
148651  148652       Not provided                      Not provided       NaN   
148652  148653       Not provided                      Not provided       NaN   

        OvertimePay  OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  \
15847          0.00   1609.00       NaN  74764.87          74764.87  2011   
15848          0.00   1206.95       NaN  74761.55          74761.55  2011   
15849       4245.85   5819.58       NaN  74759.92          74759.92  2011   
15850      25660.36    624.00       NaN  74756.76          74756.76  2011   
15851        198.04  14346.93       NaN  74751.59          74751.59  2011   
...             ...       ...       ...       ...               ...   ...   
148648         0.00      0.00       0.0      0.00              0.00  2014   
148649         0.00      0.00       0.0      0.00              0.00  2014   
148650          NaN       NaN       NaN      0.00              0.00  2014   
148651          NaN       NaN       NaN      0.00              0.00  2014   
148652          NaN       NaN       NaN      0.00              0.00  2014   

        Notes         Agency  Status  
15847     NaN  San Francisco     NaN  
15848     NaN  San Francisco     NaN  
15849     NaN  San Francisco     NaN  
15850     NaN  San Francisco     NaN  
15851     NaN  San Francisco     NaN  
...       ...            ...     ...  
148648    NaN  San Francisco     NaN  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  

[79164 rows x 13 columns]

In [151]:
# YOUR CODE IS HERE

employee_names = filtered_employees['EmployeeName'].tolist()
employee_names

['TATYANA ROTENBERG',
 'WINSTON HOM',
 'CRAIG RIGLER',
 'WENDY TAN',
 'KENNETH BREWER',
 'MAKOTO TOMONAGA',
 'BROOKE BASSETT',
 'JENNIFER COLLINS',
 'JAIME BARCIA',
 'IL CHUNG',
 'ANITA FONG',
 'JOAN RYAN',
 'MARTIN JENDRYSIK',
 'IDIL BEREKET',
 'ROGER TAM',
 'NANCY LACAP',
 'THOMAS BEEM',
 'SUSIE LAU',
 'MARC BASUINO',
 'FENDI NG',
 'RAMONA TORRES',
 'LINH TRUONG',
 'ALBERIC ANTH RIVERA',
 'FRANCISCO SOSA',
 'WILLIAM QUAN',
 'RACHAEL JOHNSON',
 'DANIEL ARANA',
 'ILARIA SALVADORI',
 'KRYSTEN LAINE',
 'VERONICA MORAN-DIAZ',
 'ANNA LISA AUSTRIA',
 'DAVID PHILLIP',
 'MELISSA RILEY',
 'CHARLES BELOV',
 'MICHAEL MAGLIULO',
 'TUCK LUM',
 'MICHAEL JULA',
 'MAURICIO MONSALVE',
 'MARY IVAS',
 'MELINEA MELSON',
 'OLIVIA MORENO',
 'ALBERT SANTOYO',
 'RAYMOND CHENG',
 'BRIAN SAIGER',
 'ALLISON CUMMINGS',
 'EMILIE CHONG',
 'DAVID CHARNEY',
 'JOHN BITNER',
 'CHANG HU',
 'TIRA ROGERS',
 'SCOTT COX',
 'RAYMOND YOUNG',
 'GILBERT FRAGOSO',
 'LENA BUTLER',
 'RICARDO MONTERO',
 'DORA GRANERA',
 'THOMAS HO

Desired Output:

![image.png](https://i.ibb.co/mtNB2TX/assignment1g.png)

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid"
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

________